[package]
name = "envrypted"
version = "0.1.0"
authors = ["higumachan <harekumo792154@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
serde_json = "*"
aes-soft = "0.3.3"
block-modes = "*"
hex-literal = "0.2.1"